stages:
  - test
  - build
  - package
  - deploy

default:
  image: node:latest
  before_script:
    - npm install
  after_script:
    - echo "success"
  cache:
    paths:
      - node_modules/

#test:
#  stage: test
#  environment:
#    name: test
#  script:
#    - npm run test
#    - npm run test:e2e
#  only:
#    - tags
#    - dev
#    - master
#  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'


build:
  stage: build
  environment:
    name: build
  script:
    - npm run build
  artifacts:
    paths:
      - ./dist/
      - ./package.json
  only:
    - tags
    - dev
    - master
    - merge_requests

package:
  image: docker:latest
  services:
    - docker:dind
  stage: package
  environment:
    name: package
    url: https://transfonum.cf:8080
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/transfonum/mariage-serein/mariage-serein-api .
    - docker push registry.gitlab.com/transfonum/mariage-serein/mariage-serein-api
  only:
    - tags
    - dev
    - master

deploy:
  stage: deploy
  environment:
    name: production
    url: https://www.transfonum.cf:8080
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp $SSH_PRIVATE_KEY ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -t ed25519 $DOMAINE >> ~/.ssh/known_hosts
    - ssh-add
  script:
    - scp ./docker-compose.yml $USERNAME@$DOMAINE:docker-compose.yml
    - ssh $USERNAME@$DOMAINE "sudo docker stack deploy -c docker-compose.yml --with-registry-auth mariage"
    - ssh $USERNAME@$DOMAINE "sudo docker system prune -f"
  only:
    - tags
    - dev
    - master
