# [START functions_ci_cd_cloud_build_nodejs]
steps:
    - name: node:10.15.1
      entrypoint: npm
      id: 'Install dependencies'
      args: ['install']
    - name: node:10.15.1
      entrypoint: npm
      args: ['run', 'create-env']
      env:
          - 'NODE_ENV=${_NODE_ENV}'
          - 'JWT_SECRET_JWK_URI=${_JWT_SECRET_JWK_URI}'
          - 'JWT_AUDIENCE=${_JWT_AUDIENCE}'
          - 'JWT_ISSUER=${_JWT_ISSUER}'
          - 'JWT_SECRET=${_JWT_SECRET}'
          - 'JWT_ALGORITHM=${_JWT_ALGORITHM}'
          - 'DATABASE_TYPE=${_DATABASE_TYPE}'
          - 'DATABASE_HOST=${_DATABASE_HOST}'
          - 'DATABASE_USERNAME=${_DATABASE_USERNAME}'
          - 'DATABASE_PASSWORD=${_DATABASE_PASSWORD}'
          - 'DATABASE_NAME=${_DATABASE_NAME}'
          - 'DATABASE_PORT=${_DATABASE_PORT}'
          - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME}'
          - 'STRIPE_API_KEY=${_STRIPE_API_KEY}'
          - 'ELASTIC_HOST=${_ELASTIC_HOST}'
          - 'ELASTIC_APM_SECRET_TOKEN=${_ELASTIC_APM_SECRET_TOKEN}'
          - 'ELASTIC_APM_SERVER_URL=${_ELASTIC_APM_SERVER_URL}'
          - 'ACCOUNT_SID=${_ACCOUNT_SID}'
          - 'AUTH_TOKEN=${_AUTH_TOKEN}'
          - 'PHONE_NUMBER=${_PHONE_NUMBER}'
          - 'GCS_BUCKET=${_GCS_BUCKET}'
          - 'GCLOUD_PROJECT=${_GCLOUD_PROJECT}'
          - 'GCS_KEYFILE=${_GCS_KEYFILE}'
          - 'MAIL_HOST=${_MAIL_HOST}'
          - 'MAIL_PORT=${_MAIL_PORT}'
          - 'MAIL_USER=${_MAIL_USER'
          - 'MAIL_PASSWORD=${_MAIL_PASSWORD}'
          
    - name: node:10.15.1
      entrypoint: npm
      id: 'Generate Migration'
      args: ['run', 'migration:generate']
    - name: node:10.15.1
      entrypoint: npm
      id: 'Run Migration'
      args: ['run', 'migration:run']      
    - name: node:10.15.1
      entrypoint: npm
      id: 'Build Bundles'
      args: ['run', 'build']
    - name: 'gcr.io/cloud-builders/gcloud'
      id: 'Deploy to App Engine'
      args: ['app', 'deploy', '--verbosity=info']
# [END functions_ci_cd_cloud_build_nodejs]
