version: '3.7'
services:
  web:
    image: registry.gitlab.com/transfonum/mariage-serein/mariage-serein-web:latest
    environment:
      - PORT=80
    ports:
      - "8888:80"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  api:
    image: registry.gitlab.com/transfonum/mariage-serein/mariage-serein-api:latest
    environment:
      - PORT=3000
    ports:
      - "8080:3000"
    volumes:
      - "apiData:/usr/app/upload/"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
volumes:
  apiData:
