runtime: nodejs10
service: default
inbound_services:
  - warmup
automatic_scaling:
  max_idle_instances: 1
  min_idle_instances: 1
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
