"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FieldTypeEnum = {
    TEXT: 'text',
    PASSWORD: 'password',
    NUMBER: 'number',
    RADIO: 'radio',
    RADIO_STRING: 'radio-string',
    RADIO_NUMBER: 'radio-number',
    DROP_DOWN: 'dropdown',
    CHECK_BOX: 'checkbox',
    TOGGLE_NUMBER: 'toggle-number',
    TOGGLE_NUMBER_TIME: 'toggle-number-time',
    TOGGLE_CHECKBOX: 'toggle-checkbox',
    TOGGLE_SIMPLE: 'toggle-simple',
    TOGGLE_RADIO: 'toggle-radio',
    TOGGLE_NUMBER_RADIO: 'toggle-number-radio',
    TOGGLE_CHECKBOX_NUMBER: 'toggle-checkbox-number',
    CHECK_BOX_NUMBER: 'checkbox-number',
    TOGGLE_NUMBER_RADIO_LIST: 'toggle-number-radio-list',
    TOGGLE_NUMBER_LIST: 'toggle-number-list',
    TOGGLE_LIST: 'toggle-list',
    CHECKBOX_NUMBER_LIST: 'checkbox-number-list',
    TOGGLE_FORMATS_LIST: 'toggle-formats-list',
    TOGGLE_VOITURE_LIST: 'toggle-voiture-list',
    TOGGLE_NUMBER_LIST_OPTIONS: 'toggle-number-list-options',
    TOGGLE_VIN_HONNEUR_COCKTAIL_BUFFET: 'toggle-vin-honneur-cocktail-buffet',
    TOGGLE_DINNER: 'toggle-dinner',
    TOGGLE_MAJORATION: 'toggle-majoration',
    TOGGLE_PRODUITS_ACCESSOIRES: 'toggle-produits-accessoires',
    TOGGLE_PRESTATIONS: 'toggle-prestations',
};
