# [START functions_ci_cd_cloud_build_nodejs]
steps:
- name: node:10.15.1
  entrypoint: npm
  id: 'Install dependencies'
  args: ['install']
- name: node:10.15.1
  entrypoint: npm
  id: 'Build Bundles'
  args: ['run', 'build:ssr-gcp']
- name: "gcr.io/cloud-builders/gcloud"
  id: 'Deploy to App Engine'
  args: ["app", "deploy"]
timeout: "2500s"
options: 
  machineType: 'N1_HIGHCPU_8'

# [END functions_ci_cd_cloud_build_nodejs]
